---
title: "Increased hazard of mortality in cases compatible with SARS-CoV-2 variant under investigation 202012/1 - a matched cohort study"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: true
knit: (function(inputFile, encoding,...) {
  rmarkdown::render(
    inputFile,
    encoding = encoding,
    output_dir = "~/Dropbox/covid19/new-variant", output_file=paste0('new-variant-mortality-',Sys.Date(),'.pdf'))
  })
# output:
#   word_document :
#     fig_caption: yes
#     fig_width: 7
# knit: (function(inputFile, encoding,...) {
#   rmarkdown::render(
#     inputFile,
#     encoding = encoding,
#     output_dir = "~/Dropbox/covid19/new-variant", output_file=paste0('new-variant-mortality-',Sys.Date(),'.docx'))
#   })
#TODO: https://www.reed.edu/data-at-reed/software/R/markdown_multiple_reports.html
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}    

fig_width: 7
fig_height: 5
out.width: "100%"
# bibliography: current-rt.bib
# csl: current-rt.csl
# vignette: >
#  %\VignetteIndexEntry{New Variant Mortality}
#  %\VignetteEngine{knitr::rmarkdown}
#  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}

library(tidyverse)
library(patchwork)
library(survival)
library(survminer)

# optional dependency:

if (dir.exists("~/Git/standard-print-output/")) {
  devtools::load_all("~/Git/standard-print-output/")
  standardPrintOutput::setDefaults()
  spo = TRUE
} else {
  spo = FALSE
}

# devtools::load_all("~/Git/uk-covid-datatools/")
# ukcovidtools::reload()

# load functions
source("./new-variant-mortality.R")

```

```{r}
## Do the analysis ----
if(!exists("coxData")) 
  coxData = loadData()

```

## Main analysis

### 1:1 strategy

```{r}

run30none1to1 = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    ageTolerance = 10,specimenDateTolerance=1,
    modelFormula = models,resolutionStrategy = "none", filterExpr = mapType=="1:1")

run30none1to1$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()
run30none1to1$table2Data %>% filter(value == "Dead <28 days")

```
### node sampling strategy

```{r}

run30nodeSample = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    ageTolerance = 10,specimenDateTolerance=1,
    modelFormula = models,resolutionStrategy = "node sample", bootstraps = 10)

run30nodeSample$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()
run30nodeSample$table2Data %>% filter(value == "Dead <28 days")

```

### edge sampling strategy

```{r}

run30edgeSample = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    ageTolerance = 10,specimenDateTolerance=1,
    modelFormula = models,resolutionStrategy = "edge sample", bootstraps = 10)

run30edgeSample$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()
run30edgeSample$table2Data %>% filter(value == "Dead <28 days")

```

###

```{r}
models = list(
  `S gene only`=Surv(time,status) ~ sGene, 
  `S gene + N gene CT`=Surv(time,status) ~ sGene+CT_N, 
  `S gene + age + gender` = Surv(time,status) ~ sGene+age+sex,
  `S gene + age` = Surv(time,status) ~ sGene+age,
  `S gene + all covariates` = Surv(time,status) ~ sGene+age+sex+imd_decile+ethnicity_final #+residential_category
)

sGeneOnly = list(
  `S gene only`=Surv(time,status) ~ sGene
)

#if(!exists("run30")) 
  run30 = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    ageTolerance = 5,specimenDateTolerance=1,
    modelFormula = models,resolutionStrategy = "none",includeRaw=TRUE,includeMatched = TRUE)
  # run30 = runAnalysis(
  #   coxData, sGeneCtThreshold = 30, ctThreshold = 30,
  #   bootstraps = 10,ageTolerance = 3,specimenDateTolerance=5,
  #   modelFormula = models,
  #   includeRaw=TRUE,includeMatched = TRUE)


p1 = ggplot(run30$coxMatchedData, aes(x=time,colour=sGene,linetype=deathStatus))+geom_line(stat="count")+scale_y_log10()
p2 = ggplot(run30$coxMatchedData %>% filter(status==0),aes(x=time,colour=sGene))+ stat_ecdf(geom = "step")+ylab("P(censored before t|censored)")
p3 = ggplot(run30$coxMatchedData %>% filter(status==1),aes(x=time,colour=sGene))+ stat_ecdf(geom = "step")+ylab("P(died before t|died)")

p1+p2+p3+patchwork::plot_annotation(tag_levels = "A")+patchwork::plot_layout(guides="collect")
rm(p1,p2,p3)
```

## Pair matching

```{r}

tmp = run30$pairedMatchedUnfilteredData %>% group_by(order.neg,order.pos) %>% summarise(n=n(), meanDate = mean((as.numeric(specimen_date.neg)+as.numeric(specimen_date.pos)/2)))
midpoint = as.numeric((min(tmp$meanDate))+as.numeric(max(tmp$meanDate)))/2
ggplot(tmp,aes(x=order.neg,y=order.pos,fill=n)) + geom_tile()# +geom_label()
ggplot(tmp %>% filter(order.neg<11,order.pos<11), aes(x=order.neg,y=order.pos,fill=n,label=n)) + geom_tile() +geom_text(colour="white")
ggplot(tmp, aes(x=order.neg,y=order.pos,fill=as.numeric(meanDate),label=n)) + geom_tile()+scale_fill_gradient2(low="purple",high="green",mid="yellow",midpoint = midpoint)
```





### Median sample KM curve

```{r}
tmp = run30none$table4Data %>% filter(model=="S gene only") %>% group_by(boot) %>% summarise(mean.HR = mean(HR)) %>% ungroup() 
middleBoot = which.min(abs(tmp$mean.HR-median(tmp$mean.HR)))
kmfit = survminer::surv_fit(Surv(time,status) ~ sGene, run30$coxMatchedData %>% filter(boot==middleBoot))
ggs = survminer::ggsurvplot(kmfit, conf.int = TRUE)
fig1 = ggs$plot+coord_cartesian(ylim=c(0.995,1))
if(spo) {
  (fig1+standardPrintOutput::defaultFigureLayout()+standardPrintOutput::narrower())  %>% 
    standardPrintOutput::saveSixthPageFigure("~/Dropbox/covid19/new-variant/KMCurve")
} else {
  fig1
}
# rm(ggs,kmfit,fig1,tmp)
```
### Summary table

```{r}

if(spo) {
  run30$table2Data %>% group_by(category) %>% 
    standardPrintOutput::saveTable("~/Dropbox/covid19/new-variant/CaseMatchedSummaryTable",defaultFontSize = 8)
} else {
  knitr::kable(run30$table2Data)
}
```

### HR table

```{r}
summary = summariseAnalysisRun(run30)
if(spo) {
  prettyPrintSummary(summary) %>% 
    standardPrintOutput::saveTable("~/Dropbox/covid19/new-variant/HRSummaryTable",defaultFontSize = 8)
} else {
  knitr::kable(prettyPrintSummary(summary))
}

```
## Do we need to do a full model of all covariates?

* Even though we have in theory controlled for them all
* Output generally shows that we don;t need it.

```{r}

tmp = bootstrappedCoxModel(run30$coxMatchedData, "Full model", Surv(time,status) ~ sGene+age+sex+imd_decile+CT_N)
tmp %>% combineBootstraps() %>% prettyPrintSummary()

```


## Biases in matched data set

```{r}
#ggplot(summaryAgeTol,aes(x=ageTolerance,y=mean.ageDifference))+geom_bar(stat="identity")

## Check for residual biases in case matched data set ----
# small mean age difference and specimen date difference
# no obvious pattern in admission delays
# CT values lower in sGene negative and in those who died. This is ? feature of sGene neg infection
# specimen dates reasonably distributed in time given that the sGene negative numbers increasing. Could constrain analysis to post Dec only.

# There is a mean age difference of `r sprintf("%1.1f",deltas$ageDifference)` years.
# There is a mean specimen date difference of `r sprintf("%1.1f",deltas$specimenDateDifference)` years.

p1 = ggplot(run30$coxMatchedData,aes(fill=sGene,x=admissionDelay))+
  geom_bar(aes(y = ..prop..), stat="count",position=position_dodge(width=0.7), width = 0.6)+
  ylab("probability")+
  xlab("Days to admission")+
  coord_cartesian(xlim=c(0,15))+
  facet_wrap(~sGene, scales = "free_y", ncol=1)+
  scale_fill_brewer(palette="Set1",guide="none")

p2 = ggplot(run30$coxMatchedData,aes(x=sGene,colour=deathStatus,y=CT_N))+geom_boxplot()+ylab("N Gene CT value")+
  scale_color_brewer(palette="Set2")+
  xlab("S gene status")+theme(legend.position = "bottom")

p3 = ggplot(run30$coxMatchedData,aes(fill=sGene,x=specimen_date))+
  geom_bar(stat="count",position=position_dodge(width=0.7), width = 0.6)+
  ylab("count")+
  xlab("Date")+
  facet_wrap(~sGene, scales = "free_y", ncol=1)+scale_fill_brewer(palette="Set1",guide="none")+xlab("date")

fig2 = p1+p3+p2+patchwork::plot_annotation(tag_levels = "A")+patchwork::plot_layout(ncol=3)

if(spo) {
  (fig2+standardPrintOutput::defaultFigureLayout())  %>% 
    standardPrintOutput::saveThirdPageFigure("~/Dropbox/covid19/new-variant/ResidualBiases")
} else {
  fig2
}
```

## 

```{r}
run30$params
run30$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()
run30$table5Data  %>% combineBootstraps() %>% prettyPrintSummary()


run30$pairedMatchedUnfilteredData %>% nrow()
run30$pairedMatchedUnfilteredData %>% distinct(FINALID.neg, FINALID.pos) %>% nrow()

run30drop = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    bootstraps = 10,ageTolerance = 3,specimenDateTolerance=5,
    modelFormula = sGeneOnly,resolutionStrategy = "drop",ratio.neg=1,ratio.pos=1)

run30drop$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()
run30drop$table5Data  %>% combineBootstraps() %>% prettyPrintSummary()

run30none = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    ageTolerance = 1,specimenDateTolerance=1,
    modelFormula = models,resolutionStrategy = "none")

run30none$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()
run30none$table5Data  %>% combineBootstraps() %>% prettyPrintSummary()

run30noneNot1to1 = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    ageTolerance = 2,specimenDateTolerance=4,
    modelFormula = models,resolutionStrategy = "none", filterExpr = mapType!="1:1")
run30noneNot1to1$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()

run30noneNot1to1 = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    ageTolerance = 2,specimenDateTolerance=4,
    modelFormula = models,resolutionStrategy = "none", filterExpr = mapType=="1:1")
run30noneNot1to1$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()


run30drop2 = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    bootstraps = 10,ageTolerance = 10,specimenDateTolerance=1,
    modelFormula = models,resolutionStrategy = "drop",ratio.neg=1:2,ratio.pos=1:2)

run30drop2$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()
run30drop2$table5Data  %>% combineBootstraps() %>% prettyPrintSummary()


run30drop3 = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    bootstraps = 10,ageTolerance = 3,specimenDateTolerance=5,
    modelFormula = sGeneOnly,resolutionStrategy = "drop",ratio.neg=1,ratio.pos=3)
run30drop3$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()


run30none2 = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    bootstraps = 10,ageTolerance = 10,specimenDateTolerance=1,
    modelFormula = models,resolutionStrategy = "none")

run30none2$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()


run30none1to1 = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    ageTolerance = 10,specimenDateTolerance=1,
    modelFormula = models,resolutionStrategy = "none", filterExpr = mapType=="1:1")
run30none1to1$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()

run30drop1to1 = runAnalysis(
    coxData, sGeneCtThreshold = 30, ctThreshold = 30,
    bootstraps = 10,ageTolerance = 10,specimenDateTolerance=1,
    modelFormula = models,resolutionStrategy = "drop",ratio.neg=1,ratio.pos=1)

run30drop1to1$table4Data  %>% combineBootstraps() %>% prettyPrintSummary()


```

## Sensitivity analysis

```{r}

if (!exists("summaryCT")) {
  summaryCT = NULL
  for(ct in seq(20,35,1)) {
    run = runAnalysis(coxData, ctThreshold = ct,bootstraps = 25,max=Inf)
    summaryCT = summaryCT %>% bind_rows(summariseAnalysisRun(run))
  }
}
p1 = ggplot(summaryCT %>% filter(model=="S gene only"), aes(x=ctThreshold, y=mean.HR,ymin=mean.HR.lower,ymax=mean.HR.upper))+geom_point()+geom_errorbar()+xlab("CT threshold")+ylab("Hazard rate")#+
  #geom_smooth(method = "lm",formula = y ~ poly(x, 2),se=TRUE,alpha=0.5)
  #geom_smooth(method = "lm",se=TRUE,alpha=0.5)

```

```{r}
if (!exists("summaryDateTol")) {
  summaryDateTol = NULL
  for(dateTol in c(0:14)) {
    run = runAnalysis(coxData, specimenDateTolerance = dateTol,bootstraps = 25)
    summaryDateTol = summaryDateTol %>% bind_rows(summariseAnalysisRun(run))
  }
}

p2 = ggplot(summaryDateTol %>% filter(model=="S gene only"), aes(x=specimenDateTolerance, y=mean.HR,ymin=mean.HR.lower,ymax=mean.HR.upper))+geom_point()+geom_errorbar()+xlab("Mismatch tolerance - sample date (days)")+ylab("Hazard rate")+
  #geom_smooth(method = "lm",formula = y ~ poly(x, 2),se=TRUE,alpha=0.5)
  #geom_smooth(method = "lm",se=TRUE,alpha=0.5)+
  scale_x_continuous(breaks = c(0,7,14))

p4 = ggplot(summaryDateTol %>% filter(model=="S gene only"),aes(x=specimenDateTolerance,y=mean.specimenDateDifference))+geom_bar(stat="identity", width=0.7, fill="steelblue") + 
  xlab("Mismatch tolerance - sample date (days)")+ylab("Pairwise bias (days)")+scale_x_continuous(breaks = c(0,7,14))

```

```{r}
if (!exists("summaryAgeTol")) {
  summaryAgeTol = NULL
  for(ageTol in c(0,1,2,3,4,5,6,7,8,9)) {
    run = runAnalysis(coxData, ageTolerance = ageTol,bootstraps = 25)
    summaryAgeTol = summaryAgeTol %>% bind_rows(summariseAnalysisRun(run))
  }
}

p3 = ggplot(summaryAgeTol %>% filter(model=="S gene only"), aes(x=ageTolerance, y=mean.HR,ymin=mean.HR.lower,ymax=mean.HR.upper))+geom_point()+geom_errorbar()+xlab("Mismatch tolerance - age (years)")+ylab("Hazard rate")+
  #geom_smooth(method = "lm",formula = y ~ poly(x, 2),se=TRUE,alpha=0.5)
  #geom_smooth(method = "lm",se=TRUE,alpha=0.5)+
  scale_x_continuous(breaks = c(0,3,6,9))
```

```{r}
fig3 = p1+p2+p3+p4+patchwork::plot_annotation(tag_levels = "A")+patchwork::plot_layout(ncol=2)
if(spo) {
  fig3 %>% 
    standardPrintOutput::saveHalfPageFigure("~/Dropbox/covid19/new-variant/SensitivityAnalysis")
} else {
  fig3
}
```

